# action.yml
name: 'Pre-build Dev Container'
description: 'Pre-builds a dev container image with optional caching'
author: 'Miguel Rodo <miguel.rodo@uct.ac.za>'
inputs:
  use_cache:
    description: 'Use cache when building the image'
    required: false
    default: 'false'
  image_name:
    description: 'Name of the image to build'
    required: false
    default: ''
  GITHUB_TOKEN:
    description: 'GitHub token for authentication'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set USE_CACHE variable
      shell: bash
      env:
        USE_CACHE: "${{ inputs.use_cache }}"
      run: |
        echo "USE_CACHE=${USE_CACHE}" >> $GITHUB_ENV

    - name: Checkout (GitHub)
      uses: actions/checkout@v4

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.GITHUB_TOKEN }}

    - name: Set lowercase image name
      shell: bash
      env:
        IMAGE_NAME_INPUT: "${{ inputs.image_name }}"
        GITHUB_REPOSITORY: "${{ github.repository }}"
      run: |
        if [ -z "${IMAGE_NAME_INPUT}" ]; then
          IMAGE_NAME="ghcr.io/${GITHUB_REPOSITORY,,}"
        else
          IMAGE_NAME="${IMAGE_NAME_INPUT}"
        fi
        echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

    - name: Debug IMAGE_NAME
      shell: bash
      env:
        IMAGE_NAME: "${{ env.IMAGE_NAME }}"
      run: |
        echo "IMAGE_NAME is set to: $IMAGE_NAME"

    - name: Set GITHUB_TOKEN for subsequent steps
      shell: bash
      env:
        GITHUB_TOKEN: "${{ inputs.GITHUB_TOKEN }}"
      run: |
        echo "GITHUB_TOKEN=${GITHUB_TOKEN}" >> $GITHUB_ENV

    - name: Pre-build dev container image (with cache)
      if: env.USE_CACHE == 'true'
      uses: devcontainers/ci@v0.3
      with:
        imageName: ${{ env.IMAGE_NAME }}
        cacheFrom: ${{ env.IMAGE_NAME }}
        push: always

    - name: Pre-build dev container image (without cache)
      if: env.USE_CACHE != 'true'
      uses: devcontainers/ci@v0.3
      with:
        imageName: ${{ env.IMAGE_NAME }}
        push: always

    - name: Update or create prebuild/devcontainer.json
      shell: bash
      env:
        IMAGE_NAME: "${{ env.IMAGE_NAME }}"
      run: |
        # Define the paths
        DEVCONTAINER_JSON=".devcontainer/devcontainer.json"
        PREBUILD_JSON=".devcontainer/prebuild/devcontainer.json"

        # Create the prebuild directory if it doesn't exist
        mkdir -p "$(dirname "$PREBUILD_JSON")"

        # If prebuild/devcontainer.json exists, update the image line
        if [ -f "$PREBUILD_JSON" ]; then
          jq --arg image "$IMAGE_NAME" '.image = $image' "$PREBUILD_JSON" > temp.json && mv temp.json "$PREBUILD_JSON"
        else
          # If prebuild/devcontainer.json doesn't exist, copy only the customizations and set the image
          if [ -f "$DEVCONTAINER_JSON" ]; then
            jq --arg image "$IMAGE_NAME" \
              '{image: $image, customizations: .customizations}' \
              "$DEVCONTAINER_JSON" > "$PREBUILD_JSON"
          else
            echo "No devcontainer.json found to copy customizations from!"
            exit 1
          fi
        fi

    - name: Commit and push changes
      shell: bash
      env:
        GITHUB_TOKEN: "${{ inputs.GITHUB_TOKEN }}"
        GITHUB_REPOSITORY: "${{ github.repository }}"
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add .devcontainer/prebuild/devcontainer.json

        # Check if there is anything to commit
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update prebuild devcontainer.json with the latest image"
          # Set up the remote URL with the GITHUB_TOKEN for authentication
          git remote set-url origin "https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
          
          # Fetch the latest changes from the remote repository
          git fetch origin

          # Attempt to fast-forward merge
          if git merge --ff-only origin/$(git rev-parse --abbrev-ref HEAD); then
            echo "Fast-forwarded successfully. Pushing changes..."
            git push
          else
            echo "Could not fast-forward. Not pushing changes."
          fi
        fi
